### PR TITLE
DON'T USE PLUGIN FROM THIS GUY, HE STEALS 30% OF YOUR MONEY!

### PR DESCRIPTION
**Pull request by Be4t5**
Hi every one, don't use
https://github.com/floatinghotpot/cordova-plugin-facebookads
or
https://github.com/floatinghotpot/cordova-admob-pro

These plugins includes a precompiled .jar for "license system check" that share with the plugin author 30% of you traffic.

If you sniff the http traffic of your app with the plugin installed, you'll notice an http request to http://adlic.rjfun.com/adlic that returns a response with a "r" parameters set to "30". This means that you are sharing the 30% of you traffic.

I know that the license says the if you don't pay the 20$ license, you are agree with sharing the 2% of you traffic.

If use in commercial project, please get a license, or, you have monetized more than $1000 using this plugin, you are also required to: either get a commercial license ($20), or, no need pay but share 2% Ad traffic, read the License Agreement for details. As a commercial customer, you will be supported with high priority, via private email or even Skype chat.

BUT 30% is NOT 2%!!!

I found out that a guy on ionic forum had exactly the same problem. The plugin author remove his issue and then removed the issue tab from admob pro.
Here's the topic:
https://forum.ionicframework.com/t/don-t-use-admob-pro-plugin-steal-30/90245

And here's the pdf with the emails that he wrote to the plugin author:
https://drive.google.com/file/d/0B5vtpya8P4b-NUZTdUhBVkFlU0E/view?usp=sharing

I tried to write 3/4 emails to the plugin author 3 weeks ago asking for explainations, but still got no answer.

I believe this is very incorrect, a real scam.

### CODE REVIEW

**Comment by MichiHory** [comment]
Sorry, but I do not know what to do, where else I can contact the developer. I bought license for this plugin on http://rjfun.github.io but do not recieved license key or instructions how to use license, only lost money.

I sent mails to liming.xie@gmail.com and rjfun.mobile@gmail.com but never recieved response (it is more than five months without response). I also  tried to solve it via PayPal, but they can' t send me money back and developer did not respond to ticket.

**Comment by Be4t5** [comment]
> Sorry, but I do not know what to do, where else I can contact the developer. I bought license for this plugin on http://rjfun.github.io but do not recieved license key or instructions how to use license, only lost money.
> 
> I sent mails to [liming.xie@gmail.com](mailto:liming.xie@gmail.com) and [rjfun.mobile@gmail.com](mailto:rjfun.mobile@gmail.com) but never recieved response (it is more than five months without response). I also tried to solve it via PayPal, but they can' t send me money back and developer did not respond to ticket.

This guy is scamming us. He steals traffic and  he does not respond to emails. Don't use his plugin, use this one https://admob-plus.github.io/

**Comment by realn3rd** [comment]
> plus

Thanks for the information.

I removed this plugin immediately and switched over the Admob Plus. This works like charm.

**Comment by Be4t5** [comment]
@floatinghotpot  Instead of hiding proofs and closing the thread, give us an explanation and give us our money back!

**Pull request closed without merging**
