### PR TITLE
Question - ADMOB_APP_ID with Phonegap Build

### PR DESCRIPTION
**Pull request by mikael-onsilva**
Hello,

I'm facing some troubles to use the plugin after this last update.
At the README it says that I need to put this code at my config.xml file

 `<preference name="android-build-tool" value="gradle" />`
`<preference name="phonegap-version" value="cli-7.1.0" />`
`<plugin name="cordova-plugin-admobpro" source="npm">`
`<variable name="PLAY_SERVICES_VERSION" value="16.0.0" />`
`</plugin>`

But I'm still having this error on phonegap build

> Error - One of your plugins requires a parameter: ADMOB_APP_ID - You can fix this here

What am I missing?

Thanks.

### CODE REVIEW

**Comment by mikael-onsilva** [comment]
I've got the error. It's necessary to add the tag

`<variable name="ADMOB_APP_ID" value="YOUR_APP_ID" />`

at the config.xml with the rest of the code shown at the README.
If possible, update it.

**Comment by phiferd** [comment]
I know this issue is closed, but if you can clarify the right value to put here if you build for both Android and iOS, that would be helpful.

AdMob App Ids are different for each platform (although they are identical up until the "~"). Does it matter which one I use, or does the plugin ignore everything after the "~"?

**Comment by mikael-onsilva** [comment]
Currently I'm just building for Android. My config.xml looked like this:

`<plugin name="cordova-plugin-admobpro" source="npm">
    <variable name="PLAY_SERVICES_VERSION" value="16.0.0" />
    <variable name="ADMOB_APP_ID" value="ca-app-pub-xxxx" />
</plugin>`

> 

> Does it matter which one I use, or does the plugin ignore everything after the "~" ?

This I don't know.

Hope it does help.

**Comment by floatinghotpot** [comment]
the App ID includes ~ and everything behind it.

**Comment by eyalish** [comment]
This doesn't seem to work for me on version 2.49.0 , using Cli-9.0.0
the only way it works for me is with your older version, 2.37.2 with cli-9.0.0.
Any reasons  ? @floatinghotpot

**Pull request closed without merging**
